#!/usr/bin/env python3
"""
Generate self-hosted GitHub profile analytics as SVG files.

The script intentionally avoids github-readme-stats/Vercel.
GitHub Actions supplies GITHUB_TOKEN automatically.
"""

from __future__ import annotations

import os
import time
from collections import Counter
from pathlib import Path
from typing import Any

import requests

USERNAME = "2171001"
API = "https://api.github.com"
OUTPUT_DIR = Path("assets")
TOKEN = os.getenv("GITHUB_TOKEN", "")

HEADERS = {
    "Accept": "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
}
if TOKEN:
    HEADERS["Authorization"] = f"Bearer {TOKEN}"

SESSION = requests.Session()
SESSION.headers.update(HEADERS)


def api_get(path: str, params: dict[str, Any] | None = None) -> Any:
    url = f"{API}{path}"

    for attempt in range(4):
        response = SESSION.get(url, params=params, timeout=30)

        if response.status_code == 403 and "rate limit" in response.text.lower():
            time.sleep(2 ** attempt)
            continue

        response.raise_for_status()
        return response.json()

    raise RuntimeError(f"GitHub API request failed: {url}")


def get_user() -> dict[str, Any]:
    return api_get(f"/users/{USERNAME}")


def get_repositories() -> list[dict[str, Any]]:
    repositories: list[dict[str, Any]] = []
    page = 1

    while True:
        batch = api_get(
            f"/users/{USERNAME}/repos",
            {
                "per_page": 100,
                "page": page,
                "type": "owner",
                "sort": "updated",
            },
        )

        if not batch:
            break

        repositories.extend(batch)

        if len(batch) < 100:
            break

        page += 1

    return repositories


def get_languages(repo: dict[str, Any]) -> dict[str, int]:
    return api_get(f"/repos/{USERNAME}/{repo['name']}/languages")


def escape_svg(value: str) -> str:
    return (
        value.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def write(path: str, content: str) -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUTPUT_DIR / path).write_text(content, encoding="utf-8")


def generate_stats(user: dict[str, Any], repos: list[dict[str, Any]]) -> None:
    stars = sum(repo.get("stargazers_count", 0) for repo in repos)
    forks = sum(repo.get("forks_count", 0) for repo in repos)

    languages_used = len(
        {
            language
            for repo in repos
            for language in get_languages(repo).keys()
        }
    )

    width = 760
    height = 270

    svg = f"""<svg xmlns="http://www.w3.org/2000/svg"
width="{width}" height="{height}" viewBox="0 0 {width} {height}">
<rect width="100%" height="100%" rx="16" fill="#0d1117" stroke="#30363d"/>
<text x="36" y="48" fill="#58a6ff" font-family="Arial,Helvetica,sans-serif"
font-size="25" font-weight="700">GitHub Statistics</text>
<text x="36" y="76" fill="#8b949e" font-family="Arial,Helvetica,sans-serif"
font-size="13">Live data generated by GitHub Actions</text>

<text x="36" y="128" fill="#8b949e" font-family="Arial,Helvetica,sans-serif"
font-size="14">Public Repositories</text>
<text x="36" y="158" fill="#f0f6fc" font-family="Arial,Helvetica,sans-serif"
font-size="25" font-weight="700">{user.get('public_repos', 0)}</text>

<text x="220" y="128" fill="#8b949e" font-family="Arial,Helvetica,sans-serif"
font-size="14">Stars</text>
<text x="220" y="158" fill="#f0f6fc" font-family="Arial,Helvetica,sans-serif"
font-size="25" font-weight="700">{stars}</text>

<text x="350" y="128" fill="#8b949e" font-family="Arial,Helvetica,sans-serif"
font-size="14">Forks</text>
<text x="350" y="158" fill="#f0f6fc" font-family="Arial,Helvetica,sans-serif"
font-size="25" font-weight="700">{forks}</text>

<text x="480" y="128" fill="#8b9498" font-family="Arial,Helvetica,sans-serif"
font-size="14">Followers</text>
<text x="480" y="158" fill="#f0f6fc" font-family="Arial,Helvetica,sans-serif"
font-size="25" font-weight="700">{user.get('followers', 0)}</text>

<text x="620" y="128" fill="#8b9498" font-family="Arial,Helvetica,sans-serif"
font-size="14">Languages</text>
<text x="620" y="158" fill="#f0f6fc" font-family="Arial,Helvetica,sans-serif"
font-size="25" font-weight="700">{languages_used}</text>

<line x1="36" y1="190" x2="724" y2="190" stroke="#21262d"/>

<text x="36" y="222" fill="#8b949e" font-family="Arial,Helvetica,sans-serif"
font-size="13">Following</text>
<text x="36" y="246" fill="#c9d1d9" font-family="Arial,Helvetica,sans-serif"
font-size="17">{user.get('following', 0)}</text>

<text x="160" y="222" fill="#8b949e" font-family="Arial,Helvetica,sans-serif"
font-size="13">Account</text>
<text x="160" y="246" fill="#c9d1d9" font-family="Arial,Helvetica,sans-serif"
font-size="17">{escape_svg(user.get('login', USERNAME))}</text>

<text x="520" y="246" fill="#8b949e" font-family="Arial,Helvetica,sans-serif"
font-size="11">Updated automatically</text>
</svg>
"""

    write("github-stats.svg", svg)


def generate_languages(repos: list[dict[str, Any]]) -> None:
    totals: Counter[str] = Counter()

    for repo in repos:
        totals.update(get_languages(repo))

    top = totals.most_common(8)
    total_bytes = sum(totals.values()) or 1

    width = 760
    height = 270

    rows = []
    start_y = 92
    row_gap = 22

    for index, (language, count) in enumerate(top):
        percentage = count / total_bytes * 100
        y = start_y + index * row_gap
        bar_width = max(2, int(percentage * 4.8))

        rows.append(
            f"""
<text x="36" y="{y}" fill="#c9d1d9"
font-family="Arial,Helvetica,sans-serif" font-size="13">{escape_svg(language)}</text>
<rect x="170" y="{y-11}" width="480" height="8" rx="4" fill="#21262d"/>
<rect x="170" y="{y-11}" width="{bar_width}" height="8" rx="4" fill="#58a6ff"/>
<text x="680" y="{y}" text-anchor="end" fill="#8b949e"
font-family="Arial,Helvetica,sans-serif" font-size="12">{percentage:.1f}%</text>
"""
        )

    if not rows:
        rows.append(
            '<text x="36" y="120" fill="#8b949e" font-family="Arial,Helvetica,sans-serif" font-size="14">No language data available yet.</text>'
        )

    svg = f"""<svg xmlns="http://www.w3.org/2000/svg"
width="{width}" height="{height}" viewBox="0 0 {width} {height}">
<rect width="100%" height="100%" rx="16" fill="#0d1117" stroke="#30363d"/>
<text x="36" y="48" fill="#58a6ff" font-family="Arial,Helvetica,sans-serif"
font-size="25" font-weight="700">Top Languages</text>
<text x="36" y="70" fill="#8b949e" font-family="Arial,Helvetica,sans-serif"
font-size="12">Based on language bytes across public repositories</text>
{''.join(rows)}
</svg>
"""

    write("top-languages.svg", svg)


def generate_activity(user: dict[str, Any], repos: list[dict[str, Any]]) -> None:
    """Create a lightweight repository activity card without external widgets."""

    recent = sorted(
        repos,
        key=lambda repo: repo.get("pushed_at") or "",
        reverse=True,
    )[:7]

    width = 1540
    height = 260

    rows = []
    y = 88

    for repo in recent:
        name = escape_svg(repo["name"])
        pushed = (repo.get("pushed_at") or "unknown")[:10]
        stars = repo.get("stargazers_count", 0)

        rows.append(
            f"""
<text x="44" y="{y}" fill="#c9d1d9"
font-family="Arial,Helvetica,sans-serif" font-size="14">{name}</text>
<text x="560" y="{y}" fill="#8b949e"
font-family="Arial,Helvetica,sans-serif" font-size="13">{pushed}</text>
<text x="760" y="{y}" fill="#8b949e"
font-family="Arial,Helvetica,sans-serif" font-size="13">★ {stars}</text>
"""
        )
        y += 23

    if not rows:
        rows.append(
            '<text x="44" y="105" fill="#8b949e" font-family="Arial,Helvetica,sans-serif" font-size="14">No public repositories found.</text>'
        )

    svg = f"""<svg xmlns="http://www.w3.org/2000/svg"
width="{width}" height="{height}" viewBox="0 0 {width} {height}">
<rect width="100%" height="100%" rx="16" fill="#0d1117" stroke="#30363d"/>
<text x="44" y="42" fill="#58a6ff" font-family="Arial,Helvetica,sans-serif"
font-size="25" font-weight="700">Repository Activity</text>
<text x="44" y="64" fill="#8b949e" font-family="Arial,Helvetica,sans-serif"
font-size="12">Most recently pushed public repositories</text>
<text x="44" y="83" fill="#8b949e" font-family="Arial,Helvetica,sans-serif"
font-size="11">Repository</text>
<text x="560" y="83" fill="#8b949e" font-family="Arial,Helvetica,sans-serif"
font-size="11">Last push</text>
<text x="760" y="83" fill="#8b949e" font-family="Arial,Helvetica,sans-serif"
font-size="11">Stars</text>
{''.join(rows)}
</svg>
"""

    write("activity.svg", svg)


def main() -> None:
    user = get_user()
    repos = get_repositories()

    generate_stats(user, repos)
    generate_languages(repos)
    generate_activity(user, repos)

    print("Generated assets/github-stats.svg")
    print("Generated assets/top-languages.svg")
    print("Generated assets/activity.svg")


if __name__ == "__main__":
    main()
